services:
  telegram:
    image: telegram
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      PASSWORD: ${PASSWORD}
      JIRA_TOKEN: ${JIRA_TOKEN}
      JIRA_HOST: http://jira:8080
      JIRA_DOMAINNAME: http://jira.jestenok.com
    expose:
      - "8080"